<?php
$f3    = \Base::instance();
$title = 'My Profile';
$f3->set('title', $title);
$usersMapper = $f3->get('usersMapper');
?>
<?=\View::instance()->render('cms/header.phtml'); ?>
<?=\View::instance()->render('cms/header-menu.phtml'); ?>
<?=\View::instance()->render('cms/notifications.phtml'); ?>

<div class="container">

    <h1><?=$title ?></h1>

    <p>This is your <em>public</em> profile data.</p>

    <form method="post" action="<?=$f3->alias('profile') ?>" enctype='multipart/form-data'>
        <input type="hidden" id="csrf" name="csrf" value="<?=$f3->get('csrf') ?>">

        <fieldset>

            <legend><i class="material-icons prefix large">perm_identity</i></legend>

            <div class="row">

                <div class="input-field col s12">
                    <?php if ($url = $usersMapper->profileImageUrlDynamic(['height' => 150])): ?>
                        <img class="center-align valign-wrapper circle responsive-img" src="<?=$url?>">
                    <?php endif ?>
                    <input type="file" name="profile" id="profile">
                    <p>Profile Image (max size 4MB)</p>
                </div>

            </div>

            <div class="row">
                <div class="input-field col s12">
                    <input required class="validate" type="text" name="nickname" id="nickname" value="<?=$f3->get('form.nickname') ?>">
                    <label for="nickname">Name (as you want to appear on the website)</label>
                </div>
            </div>

            <div class="row">

                <div class="input-field col s6">
                    <textarea required name="bio" class="materialize-textarea" id="bio"><?=$f3->get('form.bio') ?></textarea>
                    <label for="bio">Bio (optionally in <a href="https://en.wikipedia.org/wiki/Markdown" target="markdown">Markdown Text Format</a>)</label>
                </div>

                <div class="col s6">
                    <div id="bio-preview"></div>
                </div>

            </div>

        </fieldset>

        <div class="center">
            <button type="submit" class="waves-effect waves-light btn btn-large green darken-1" id="update_profile">Update Profile</button>
        </div>

    </form>

</div>


<?=\View::instance()->render('cms/footer-menu.phtml'); ?>
<?=\View::instance()->render('cms/footer.phtml'); ?>

<script type="text/javascript">

function updateBio(){
    updateBio.refreshes--;
    $('#bio-preview').html(updateBio.converter.makeHtml($('#bio').val()));
    if (updateBio.refreshes > 0) {
        setTimeout(updateBio, 250);
    }
}
updateBio.converter =  new showdown.Converter();
updateBio.refreshes = 5000;

updateBio();

</script>
