<?php
use \FFCMS\Enums\ConfigTypes;

$f3 = \Base::instance();
$title = 'Add Config Data';
$f3->set('title', $title);
?>
<?=\View::instance()->render('cms/header.phtml'); ?>
<?=\View::instance()->render('cms/header-menu.phtml'); ?>
<?=\View::instance()->render('cms/notifications.phtml'); ?>

<div class="container">

    <h1><?=$title ?></h1>

    <form method="post" action="<?=$f3->alias('admin_config_add') ?>">
        <input type="hidden" id="csrf" name="csrf" value="<?=$f3->get('csrf') ?>">
        <input type="hidden" id="uuid" name="uuid" value="<?=$f3->get('form.uuid') ?>">

        <fieldset>

            <legend>Add</legend>

            <div class="input-field col s12">
                <textarea required name="description" id="description" class="materialize-textarea"><?=$f3->get('form.description') ?></textarea>
                <label for="description">Description</label>
            </div>

            <div class="input-field col s12">
                <input required  class="validate" type="text" name="key" id="key" value="<?=$f3->get('form.key') ?>">
                <label for="key">Key (will be converted to a slug)</label>
            </div>

            <div class="input-field col s12">
              <select required class="validate" type="text" name="type" id="type" value="<?=$f3->get('form.type') ?>">
                <option value="" disabled selected>Data Type</option>
                <?php
                    $types = ConfigTypes::values();
                    foreach ($types as $type => $name): ?>
                        <option value="<?=$type ?>"><?=$name ?></option>
                    <?php endforeach; ?>
              </select>
            </div>

            <div class="center">
                <button class="waves-effect waves-light btn btn-large green darken-1">Add Data Item</button>
                <p><b>Note:</b> You must enter the value on the edit page afterwards.</p>
            </div>

        </fieldset>

    </form>

</div>


<?=\View::instance()->render('cms/footer-menu.phtml'); ?>
<?=\View::instance()->render('cms/footer.phtml'); ?>
