<?php
$f3    = \Base::instance();
$title = 'My Apps';
$f3->set('title', $title);
?>
<?=\View::instance()->render('cms/header.phtml'); ?>
<?=\View::instance()->render('cms/header-menu.phtml'); ?>
<?=\View::instance()->render('cms/notifications.phtml'); ?>

<div class="container">

    <h1><?=$title ?></h1>

    <div class="row">

        <div class="col s12">
            <ul class="tabs">
                <li class="tab col s6"><a href="#create">Create</a></li>
                <li class="tab col s6"><a href="#registered">Registered</a></li>
            </ul>
        </div>

        <div id="create" class="col s12">

            <h2>Create</h2>

            <p>To create an app, please fill out the form below which will go through our manual approval process.</p>

            <form method="post" action="<?=$f3->alias('app_register') ?>">
                <input type="hidden" id="csrf" name="csrf" value="<?=$f3->get('csrf') ?>">
                <fieldset>
                    <legend><i class="material-icons prefix large">phonelink_setup</i></legend>
                    <div class="input-field col s12">
                        <input required class="validate" type="text" name="name" value="<?=$f3->get('form.name') ?>" id="name">
                        <label for="name">Name</label>
                    </div>
                    <div class="input-field col s12">
                        <textarea required name="description" class="materialize-textarea" id="description"><?=$f3->get('form.description') ?></textarea>
                        <label for="logo_url">Description</label>
                    </div>
                    <div class="input-field col s12">
                        <input required  class="validate" type="text" name="callback_uri" value="<?=$f3->get('form.callback_uri') ?>" id="callback_uri">
                        <label for="callback_uri">Callback URI</label>
                    </div>
                    <div class="input-field col s12">
                        <textarea name="redirect_uris" class="materialize-textarea" id="redirect_uris"><?=$f3->get('form.redirect_uris') ?></textarea>
                        <label for="redirect_uris">Redirect URIs</label>
                    </div>
                    <div class="input-field col s12">
                        <input type="text" name="logo_url" value="<?=$f3->get('form.logo_url') ?>" id="logo_url">
                        <label for="logo_url">logo_url URL</label>
                    </div>
                </fieldset>

                <div class="center">
                    <button type="submit" class="waves-effect waves-light btn btn-large orange darken-1" id="submit">Submit App Request</button>
                </div>
            </form>

        </div>

        <div id="registered" class="col s12">

            <?php if ($apps = $f3->get('apps')): ?>

                <?php foreach ($apps as $a): ?>

                    <h3><?=$a->name ?></h3>

                    <form method="post" action="<?=$f3->alias('app_update') ?>">
                        <input type="hidden" id="csrf" name="csrf" value="<?=$f3->get('csrf') ?>">
                        <input type="hidden" id="client_id" name="client_id" value="<?=$a->client_id ?>">
                        <table class="responsive-table">
                            <thead>
                                <tr>
                                    <th>Client ID</th>
                                    <th>Client Secret</th>
                                    <th>Status</th>
                                    <th>Created</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td><tt class="text-tiny"><?=$a->client_id ?></tt></td>
                            <td><tt class="text-tiny"><?=$a->client_secret ?></tt></td>
                            <td><?=ucwords($a->status) ?></td>
                            <td><?=substr(date('r', strtotime($a->created)), 0, -6) ?></td>
                            </tr>
                            </tbody>
                        </table>

                        <fieldset>

                            <legend><i class="material-icons prefix large">phonelink_setup</i></legend>

                            <div class="input-field col s12">
                                <input required  class="validate" type="text" name="name" id="name" value="<?=$a->name ?>">
                                <label for="name">Name</label>
                            </div>
                            <div class="input-field col s12">
                                <textarea required name="description" id="description" class="materialize-textarea"><?=$a->description ?></textarea>
                                <label for="logo_url">Description</label>
                            </div>
                            <div class="input-field col s12">
                                <input required  class="validate" type="text" name="callback_uri" id="callback_uri" value="<?=$a->callback_uri ?>">
                                <label for="callback_uri">Callback URI</label>
                            </div>
                            <div class="input-field col s12">
                                <textarea name="redirect_uris" id="description" class="materialize-textarea"><?=$a->redirect_uris ?></textarea>
                                <label for="redirect_uris">Redirect URIs</label>
                            </div>
                            <div class="input-field col s12">
                                <input type="text" name="logo_url" id="logo_url" value="<?=$a->logo_url ?>">
                                <label for="logo_url">Logo URL</label>
                            </div>
                        </fieldset>

                        <div class="center">
                            <button class="waves-effect waves-light btn btn-large blue darken-1">Update App</button>
                        </div>

                    </form>

                <?php endforeach ?>

            <?php else: ?>

                    <p>You have no apps registered.</p>

            <?php endif ?>

        </div>

    </div>

</div>

<?=\View::instance()->render('cms/footer-menu.phtml'); ?>
<?=\View::instance()->render('cms/footer.phtml'); ?>
