<?php $f3 = \Base::instance();
$title = 'Blank';
$f3->set('title', $title);
?>
<?=\View::instance()->render('cms/header.phtml'); ?>
<?=\View::instance()->render('cms/header-menu.phtml'); ?>
<?=\View::instance()->render('cms/notifications.phtml'); ?>

<div class="container">

    <h1><?=$title ?></h1>

</div>

<?=\View::instance()->render('cms/footer-menu.phtml'); ?>
<?=\View::instance()->render('cms/footer.phtml'); ?>
