<?php $f3 = \Base::instance();
$title = 'Home';
$f3->set('title', $title);
?>
<?=\View::instance()->render('cms/header.phtml'); ?>
<?=\View::instance()->render('cms/header-menu.phtml'); ?>
<?=\View::instance()->render('cms/notifications.phtml'); ?>

<div class="container">

    <h1 class="header center">f3-cms</h1>

    <div class="center">
        <?php if (empty($f3->get('uuid'))): ?>
            <a href="<?=$f3->alias('login') ?>" class="btn btn-large blue darken-1">Login</a>
            <a href="<?=$f3->alias('register') ?>" class="btn btn-large green">Register</a>
        <?php endif ?>
        <p>This project is by <a href="http://www.urunu.com">Vijay Mahrra</a> and it is built on, and serves as, an example of the <a href="http://fatfreeframework.com/home">Fat-Free Framework</a></p>
    </div>

</div>

<?=\View::instance()->render('cms/footer-menu.phtml'); ?>
<?=\View::instance()->render('cms/footer.phtml'); ?>
