<?php
$f3    = \Base::instance();
$title = 'Edit App';
$f3->set('title', $title);
?>
<?=\View::instance()->render('cms/header.phtml'); ?>
<?=\View::instance()->render('cms/header-menu.phtml'); ?>
<?=\View::instance()->render('cms/notifications.phtml'); ?>

<div class="container">

    <h1><?=$title ?></h1>

    <div class="row">

        <div class="col s12">

            <form method="post" action="<?=$f3->alias('admin_apps_edit') ?>">
                <input type="hidden" id="csrf" name="csrf" value="<?=$f3->get('form.csrf') ?>">
                <input type="hidden" id="client_id" name="client_id" value="<?=$f3->get('form.client_id') ?>">
                <table class="responsive-table">
                    <thead>
                        <tr>
                            <th>Client ID</th>
                            <th>Client Secret</th>
                            <th>Created</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td><tt class="text-tiny"><?=$f3->get('form.client_id') ?></tt></td>
                    <td><tt class="text-tiny"><?=$f3->get('form.client_secret') ?></tt></td>
                    <td><?=substr(date('r', strtotime($f3->get('form.created'))), 0, -6) ?></td>
                    </tr>
                    </tbody>
                </table>

                <fieldset>

                    <legend><i class="material-icons prefix large">phonelink_setup</i></legend>

                    <div class="input-field col s12">
                        <input required  class="validate" type="text" name="name" id="name" value="<?=$f3->get('form.name') ?>">
                        <label for="name">Name</label>
                    </div>
                    <div class="input-field col s12">
                        <textarea required name="description" id="description" class="materialize-textarea"><?=$f3->get('form.description') ?></textarea>
                        <label for="logo_url">Description</label>
                    </div>
                    <div class="input-field col s12">
                        <input required  class="validate" type="text" name="callback_uri" id="callback_uri" value="<?=$f3->get('form.callback_uri') ?>">
                        <label for="callback_uri">Callback URI</label>
                    </div>
                    <div class="input-field col s12">
                        <textarea name="redirect_uris" id="description" class="materialize-textarea"><?=$f3->get('form.redirect_uris') ?></textarea>
                        <label for="redirect_uris">Redirect URIs</label>
                    </div>
                    <div class="input-field col s12">
                        <input type="text" name="logo_url" id="logo_url" value="<?=$f3->get('form.logo_url') ?>">
                        <label for="logo_url">Logo URL</label>
                    </div>
                    <div class="input-field col s12">
                        <input required  class="validate" type="text" name="status" id="status" value="<?=$f3->get('form.status') ?>">
                        <label for="status">Status (suspended,closed,cancelled,registered,approved)</label>
                    </div>
                </fieldset>

                <div class="center">
                    <button class="waves-effect waves-light btn btn-large blue darken-1">Update App</button>
                </div>

            </form>
        </div>

    </div>

</div>

<?=\View::instance()->render('cms/footer-menu.phtml'); ?>
<?=\View::instance()->render('cms/footer.phtml'); ?>
