<?php
$f3 = \Base::instance();
$uh = FFMVC\Helpers\Url::instance();

$user    = $f3->get('user');
$title   = 'Apps';
$results = $f3->ref('results');
$p       = & $results['pagination'];
$fields  = $p['fields'];

if (!empty($p['results'])) {
    $excludeFields = ['id', 'client_secret', 'logo_url'];
    $listFields    = array_diff($fields, $excludeFields);
}
?>
<?=\View::instance()->render('cms/header.phtml'); ?>
<?=\View::instance()->render('cms/header-menu.phtml'); ?>
<?=\View::instance()->render('cms/notifications.phtml'); ?>

<div class="container">

    <h1><a href="<?=$f3->alias('admin_apps_list') ?>"><?=$title ?></a></h1>

    <div class="row">
        <div class="col s12">

            <nav>
                <div class="nav-wrapper grey lighten-3 black-text">
                    <form action="<?=$f3->alias('admin_apps_search') ?>" action="GET">
                        <input type="hidden" name="search_type" value="fuzzy">
                        <div class="input-field">
                            <input required class="required" id="search" name="search" type="search" value="<?=$f3->get('form.search') ?>">
                            <label for="search"><i class="material-icons">search</i></label>
                            <i class="material-icons">close</i>
                        </div>
                    </form>
                </div>
            </nav>

        </div>
    </div>

    <?php if (empty($p['results'])): ?>

        <p>No results available.</p>

        <a href="<?=$f3->alias('admin_apps_list') ?>" class="waves-effect waves-light btn btn-medium blue">List all apps</a>

    <?php else: ?>

        <div class="center-align">
            <?=\View::instance()->render('cms/paginator.phtml'); ?>
        </div>

        <div class="row">
            <div class="col s12">

                <table class="responsive-table">
                    <tr>
                        <?php foreach ($listFields as $field): ?>
                            <th data-field="<?=$field ?>"><?=$field ?></th>
                        <?php endforeach ?>
                        <th>Action</th>
                    </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($results['objects'] as $k => $o):  //unset($results['objects'][$k]);  ?>
                            <tr>
                                <?php foreach ($listFields as $field):
                                        $v = $o[$field];
                                        $link = '';
                                    switch ($field) {
                                        case 'created':
                                            $v = substr(date('r', strtotime($v)), 0, -6);
                                            $class = 'text-small';
                                            break;
                                        case 'users_uuid':
                                            if ($field == 'users_uuid') {
                                                $link = $uh->internal('@admin_users_search', [
                                                    'search' => $o['users_uuid'],
                                                    'search_fields' => 'uuid',
                                                    'type' => 'exact',
                                                ]);
                                            }
                                        case 'client_id':
                                        case 'client_secret':
                                            $class = "text-tiny";
                                            break;
                                        default:
                                            $class = '';
                                    }
                                    $class = empty($class) ? '' : ' class="' . $class . '"';
                                    ?>
                                    <td>
                                        <p<?=$class ?>>
                                        <?php if (empty($link)): ?>
                                            <?=$v ?>
                                        <?php else: ?>
                                            <a href="<?=$link ?>"><?=$v ?></a>
                                        <?php endif ?>
                                        </p>
                                    </td>
                                <?php endforeach ?>
                                <td>
                                    <a href="<?=$f3->alias('admin_apps_edit') . '?client_id=' . $o['client_id'] ?>" class="waves-effect waves-light btn btn-small blue">Edit</a>
                                    <a onclick="confirmUrl('<?=$f3->alias('admin_apps_delete') . '?client_id=' . $o['client_id'] ?>')" class="waves-effect waves-light btn btn-small red">Delete</a>
                                    <a href="<?=
                                    $uh->internal('@admin_tokens_search',
                                        [
                                        'search'        => $o['client_id'],
                                        'search_fields' => 'client_id',
                                        'type'          => 'exact',
                                        'order'         => 'created DESC',
                                        'fields'        => ''
                                    ]);
                                    ?>" class="btn btn btn-medium yellow">Tokens</a>
                                </td>
                            </tr>
                            <?php endforeach ?>
                    </tbody>
                </table>

            </div>
        </div>

        <div>
        <?=\View::instance()->render('cms/paginator.phtml'); ?>
        </div>

        <p>Showing <?=$p['results_from'] ?> - <?=$p['results_to'] ?> out of <?=$p['results'] ?> results.</p>

<?php endif ?>

</div>
<?=\View::instance()->render('cms/footer-menu.phtml'); ?>
<?=\View::instance()->render('cms/footer.phtml'); ?>
