<?php
$f3    = \Base::instance();
$e     = $f3->get('ERROR');
$title = 'Error: ' . $e['code'];
$f3->set('title', $title);
$debug = $f3->get('DEBUG');
?>
<?=\View::instance()->render('cms/header.phtml'); ?>
<link rel="stylesheet" href="/css/code.css">

<div class="container">

    <h1>Error: <?=$e['code'] ?></h1>

    <p><em><?=$e['status'] ?></em><br/></p>

    <?php if ($f3->get('app.env') !== 'production'): ?>

        <?php if ($debug > 0): ?>

            <h1 class="h2">Error Context</h2>
            <pre>
            <?=$e['trace']; ?>
            </pre>

        <?php endif ?>

        <?php if ($debug > 1): ?>

            <h1 class="h2">Error Trace</h2>
            <pre>
                <?=print_r($f3->trace(null, false)); ?>
            </pre>

        <?php endif ?>

    <?php endif ?>

</div>

<?=\View::instance()->render('cms/footer.phtml'); ?>
