<?php
$f3     = \Base::instance();
$p      = $f3->get('pagesMapper');
$f3->set('page', $p->cast());
extract($p->cast());
?>
<?=\View::instance()->render('cms/header.phtml'); ?>
<?=\View::instance()->render('cms/header-menu.phtml'); ?>
<?=\View::instance()->render('cms/notifications.phtml'); ?>

<div class="container">

    <h1><?=\Markdown::instance()->convert($title) ?></h1>

    Embed a map.

    <form action="<?=$f3->alias('contact')?>">
        <button>Submit</button>
    </form>

    <?=\Markdown::instance()->convert($body) ?>

</div>

<?=\View::instance()->render('cms/footer-menu.phtml'); ?>
<?=\View::instance()->render('cms/footer.phtml'); ?>
