<?php
$f3 = \Base::instance();
$analytics = $f3->get('analytics');
$analytics['enabled'] = $analytics['enabled'] && 'production' == $f3->get('app.env');
?>
<?php if (!empty($analytics['enabled']) && !empty($analytics['code']) && !empty($analytics['domain'])): ?>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', '<?=$analytics['code'] ?>', '<?=$analytics['domain'] ?>');
  ga('send', 'pageview');
</script>
<?php endif ?>


<?php if ('production' == $f3->get('app.env')): ?>
    <script src="https://code.jquery.com/jquery-2.1.4.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.7/js/materialize.min.js"></script>
<?php else: ?>
    <script type="text/javascript" src="/js/jquery.min.js"></script>
    <script type="text/javascript" src="/js/materialize.min.js"></script>
<?php endif; ?>

<script>window.jQuery || document.write('<script src="/js/jquery.min.js"><\/script>')</script>

<script src="/js/site.js"></script>

</body>
</html>
