<?php
$f3                   = \Base::instance();
$analytics            = $f3->get('analytics');
$analytics['enabled'] = $analytics['enabled'] && 'production' == $f3->get('app.env');
?>
<?php if (!empty($analytics['enabled']) && !empty($analytics['code']) && !empty($analytics['domain'])): ?>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', '<?=$analytics['code'] ?>', '<?=$analytics['domain'] ?>');
  ga('send', 'pageview');
</script>
<?php endif ?>

<?php $js = $f3->get('js.load'); if (is_array($js)): foreach ($js as $script): ?>
    <script src="<?=$script ?>"></script>
<?php endforeach; endif ?>

<script>window.jQuery || document.write('<script src="/js/jquery.min.js"><\/script>')</script>

<script src="/js/site.js"></script>

</body>
</html>
