<?php
$f3 = \Base::instance();
$title = 'Forgot Password Reset';
$f3->set('title', $title);
?>
<?=\View::instance()->render('cms/header.phtml'); ?>
<?=\View::instance()->render('cms/header-menu.phtml'); ?>
<?=\View::instance()->render('cms/notifications.phtml'); ?>

<div class="container">


    <h1><?=$title ?></h1>

    <form  method="post" action="<?=$f3->alias('forgot_password_step3')?>">

        <input type="hidden" id="csrf" name="csrf" value="<?=$f3->get('csrf') ?>">
        <input type="hidden" name="uuid" value="<?=$f3->get('uuid') ?>">
        <input type="hidden" name="code" value="<?=$f3->get('form.code') ?>">

        <fieldset>

            <legend><i class="material-icons prefix large">lock</i></legend>

            <div class="input-field col s6">
                <input required  class="validate" type="text" name="password_answer" id="password_answer" value="<?=$f3->get('form.password_answer') ?>">
                <label for="password_answer"><?=$f3->get('password_question') ?></label>
            </div>
            <div class="input-field col s6">
                <i class="material-icons prefix">vpn_key</i>
                <input required  class="validate" type="password" name="password" id="password"  autocomplete="off" value="<?=$f3->get('form.password') ?>">
                <label for="password">Password</label>
            </div>
            <div class="input-field col s6">
                <i class="material-icons prefix">vpn_key</i>
                <input required  class="validate" type="password" name="confirm_password" id="confirm_password" autocomplete="off" value="<?=$f3->get('form.confirm_password') ?>">
                <label for="confirm_password">Confirm Password</label>
            </div>

            <div class="center">
                <button type="submit" class="waves-effect waves-light btn btn-large green darken-1" id="submit">Set New Password</button>
            </div>

        </fieldset>

    </form>

</div>

<?=\View::instance()->render('cms/footer-menu.phtml'); ?>
<?=\View::instance()->render('cms/footer.phtml'); ?>
