<?php
$f3    = \Base::instance();
$title = 'Forgot Password';
$f3->set('title', $title);
?>
<?=\View::instance()->render('cms/header.phtml'); ?>
<?=\View::instance()->render('cms/header-menu.phtml'); ?>
<?=\View::instance()->render('cms/notifications.phtml'); ?>

<div class="container">

    <h1><?=$title ?></h1>

    <form method="post" action="<?=$f3->alias('forgot_password_step1') ?>">
        <input type="hidden" id="csrf" name="csrf" value="<?=$f3->get('csrf') ?>">

        <div class="row">
            <div class="col s12">

                <fieldset>

                    <legend><i class="material-icons prefix large">vpn_key</i></legend>

                    <div class="input-field col s12">
                        <i class="material-icons prefix">mail</i>
                        <input required  class="validate" type="email" name="email" id="email"  value="<?=$f3->get('form.email') ?>">
                        <label for="email">Email</label>
                    </div>

                    <div class="center">
                        <button type="submit" class="waves-effect waves-light btn btn-large orange darken-1" id="submit">Send Password Reset Email</button>
                    </div>

                </fieldset>

            </div>
        </div>
    </form>

</div>

<?=\View::instance()->render('cms/footer-menu.phtml'); ?>
<?=\View::instance()->render('cms/footer.phtml'); ?>
