<?php
$f3 = \Base::instance();
$title = 'Forgot Password Reset';
$f3->set('title', $title);
?>
<?=\View::instance()->render('cms/header.phtml'); ?>
<?=\View::instance()->render('cms/header-menu.phtml'); ?>
<?=\View::instance()->render('cms/notifications.phtml'); ?>

<div class="container">

    <h1><?=$title ?></h1>

    <form method="post" action="<?=$f3->alias('forgot_password_step2')?>">
        <input type="hidden" id="csrf" name="csrf" value="<?=$f3->get('csrf') ?>">

        <fieldset>

            <legend><i class="material-icons prefix large">mail</i></legend>

            <div class="input-field col s6">
                <input required  class="validate" type="text" name="code" id="code" autocomplete="off" value="<?=$f3->get('form.code') ?>">
                <label for="code">Password reset code from email</label>
            </div>

            <div class="center">
                <button type="submit" class="waves-effect waves-light btn btn-large orange darken-1" id="submit">Continue to Reset Password</button>
            </div>

        </fieldset>

    </form>

</div>

<?=\View::instance()->render('cms/footer-menu.phtml'); ?>
<?=\View::instance()->render('cms/footer.phtml'); ?>
