<?php
$f3   = \Base::instance();
$user = $f3->get('user');
$uh   = FFMVC\Helpers\Url::instance();

$title   = 'Report';
$results = $f3->ref('results');
$fields  = array_keys($results[0]);
?>
<?=\View::instance()->render('cms/header.phtml'); ?>
<?=\View::instance()->render('cms/header-menu.phtml'); ?>
<?=\View::instance()->render('cms/notifications.phtml'); ?>

<div class="container">

    <h1><a href="<?=$f3->alias('admin_reports_list') ?>"><?=$title ?></a></h1>

    <div class="row">
        <div class="col s12">

            <nav>
                <div class="nav-wrapper grey lighten-3 black-text">
                    <form action="<?=$f3->alias('admin_reports_search') ?>" action="GET">
                        <input type="hidden" name="search_type" value="fuzzy">
                        <div class="input-field">
                            <input required class="required" id="search" name="search" type="search" value="<?=$f3->get('form.search') ?>">
                            <label for="search"><i class="material-icons">search</i></label>
                            <i class="material-icons">close</i>
                        </div>
                    </form>
                </div>
            </nav>

        </div>
    </div>

    <?php if (empty($results)): ?>

        <p>No results available.</p>

        <a href="<?=$f3->alias('admin_reports_list') ?>" class="waves-effect waves-light btn btn-medium blue">List all reports</a>

    <?php else: ?>

        <div class="row">
            <div class="col s12">

                <table class="responsive-table">
                    <tr>
                        <?php foreach ($fields as $field): ?>
                            <th data-field="<?=$field ?>"><?=$field ?></th>
                        <?php endforeach ?>
                    </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($results as $k => $o):  //unset($results[$k]);  ?>
                            <tr>
                                <?php foreach ($fields as $field):
                                        $v = $o[$field];
                                        $link = '';
                                    switch ($field) {
                                       case 'created':
                                            $v = substr(date('r', strtotime($v)), 0, -6);
                                            $class = 'text-small';
                                            break;
                                        case 'uuid':
                                        case 'users_uuid':
                                            $class = "text-tiny";
                                            if ($field == 'users_uuid') {
                                                $link = $uh->internal('@admin_users_search', [
                                                    'search' => $o['users_uuid'],
                                                    'search_fields' => 'uuid',
                                                    'type' => 'exact',
                                                ]);
                                            }
                                            break;
                                        default:
                                            $class = '';
                                    }
                                    $class = empty($class) ? '' : ' class="' . $class . '"';
                                    ?>
                                    <td>
                                        <p<?=$class ?>>
                                        <?php if (empty($link)): ?>
                                            <?=$v ?>
                                        <?php else: ?>
                                            <a href="<?=$link ?>"><?=$v ?></a>
                                        <?php endif ?>
                                        </p>
                                    </td>
                                <?php endforeach ?>
                            </tr>
                        <?php endforeach ?>
                    </tbody>
                </table>
            </div>
        </div>

<?php endif ?>
        <a href="<?=$f3->alias('admin_reports_add') ?>" class="waves-effect waves-light btn btn-small blue">Add New Report</a>

</div>
<?=\View::instance()->render('cms/footer-menu.phtml'); ?>
<?=\View::instance()->render('cms/footer.phtml'); ?>
